import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./reset.css";
import "./globals.css";
import { AuthProvider } from "../services/AuthContext";  // Importe o AuthProvider

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <AuthProvider>  {/* Envolvendo o conteúdo com AuthProvider */}
      <html lang="pt-br">
        <head>
          {/* Coloque os metadados ou outras tags de cabeçalho aqui */}
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {children}  {/* O conteúdo da página será injetado aqui */}
        </body>
      </html>
    </AuthProvider>
  );
}
